name: Changesets PR or Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0

      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          cache: yarn
          cache-dependency-path: yarn.lock
          node-version-file: .nvmrc

      - run: yarn install --immutable

      - name: Set git user
        run: |
          git config --global user.email "shinhyojeong.w@gmail.com"
          git config --global user.name "shinhyojeong"

      - name: Create Changesets Pull Request or Publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version
          tag: yarn changeset tag
          publish: yarn changeset publish
          title: "release: version packages"
          commit: |
            release: version packages

            Co-authored-by: Hyojeong Shin <shinhyojeong.w@gmail.com>
        env:
          GITHUB_TOKEN: ${{ secrets.AUTHOR_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
